### ISSUE TITLE
cap_net_bind_service=+ep and go run main together?

### ISSUE THREAD

**Issue by jonfriesen** [mholt/certmagic#30]
## What is your question?
How do you develop with certmagic when you need a debugger? I'd like to continue using port 80/443 /w self signed certs in VS Code without running as root.

Basically how to combine `go run /path/to/main.go` with `cap_net_bind_service=+ep`?

## What have you already tried?
I can build the binary and run `sudo setcap cap_net_bind_service=+ep /path/to/your/binary` which works but the debugger is a bit flaky when using a remote binary.

I can also run as root (but would prefer not to)  

## Include any other information or discussion.
This question is rather broad and I apologize ahead of time. I figured the likelihood of the authors here being able to help me would be very high.

Edit: If we can find a solution, I volunteer to write a little section in the readme on using certmagic locally with self signed certificates for development purposes :smile: 

## Bonus: What do you use this package for, and does it help you?
Currently unannounced project that uses certmagic (especially it's on-demand TLS feature). This library is absolutely amazing. Thanks a ton!!

**Comment by mholt** [comment]
I don't use Linux when developing, so I don't know how to answer the question, sorry.

I also don't use a debugger -- I use print statements.

But in general, I develop by forwarding ports 80 and 443 on my router to higher ports and then I configure CertMagic to use those ports, and I don't have to run as root then.

But since I don't dev the same way you do, I'm afraid I can't answer your questions, sorry! If you figure it out, I'm sure something on the wiki would be helpful for others who do it the same way.

(Since this isn't really actionable, and isn't actually about certmagic specifically, and is more of a Go programming question, I'll close the issue.)

**Comment by jonfriesen** [comment]
Appreciate the response @mholt . If I come across a solution, I'll post it here.

Cheers
